version: '4.24.2'

services:
  postgres:
    container_name: foodExplorer_API_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=foodExplorer_API